### ISSUE TITLE
The Github Flow link redirects to docs.github.com

### ISSUE THREAD

**Issue by FlurinBruehwilerCMI** [Z-100/GeoPal#2]
:notebook_with_decorative_cover: **Describe the bug**

:walking: **To Reproduce**
1. On Github go to the Wiki
2. Go to "Contributing"
3. Go to "We use Github Flow, so all code changes happen through Pull Reques"
4. In the first sentence, there is a link to Github Flow. 
5. The link address is: "https://guides.github.com/introduction/flow/index.html"

This link redirects to docs.github.com/
This is a bug.
pls fix
![Screenshot-000338](https://user-images.githubusercontent.com/69467225/224640195-675508a0-e5d7-460c-93c3-1a640b6d1aa6.png)

**Comment by FlurinBruehwilerCMI** [comment]
When will this be fixed, I will have to fork if this does not get fixed very soon. pls fix

**Comment by Z-100** [comment]
get lost
